# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@1.3.1

jobs:
  build-deploy:
    docker:
      - image: cimg/ruby:2.7.2-node
    environment:
      AWS_DEFAULT_REGION: us-gov-west-1

    steps:
      - checkout
      - aws-cli/setup
      - run: yarn install
        # If this works, think about adding it to the Gemfile
      - run: gem install bundler:1.16.6
      - run: bundle install
      - run: yarn build
      - run: bundle exec jekyll build
      - run: aws s3 ls

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  deploy:
    jobs:
      - build-deploy:
          context:
            - Platform
